namespace :configatron do
  
  # desc "Export the contents of configatron.common to public/javascripts/configatron.js"
  # task(:to_js => :environment) do
  #   js_filepath = Rails.root.join('public', 'javascripts', 'configatron.js')
  #   js = "// This file is autogenerated by running 'rake configatron:to_js'\nconfig=#{configatron.common.to_hash.to_json};"
  #   File.open(js_filepath, 'w') {|f| f.write(js) }
  # end
  
  desc "Export the contents of configatron.common.sass to app/assets/stylesheets/_config.sass"
  task(:sass => :environment) do
    sass_filepath = Rails.root.join('app', 'assets', 'stylesheets', '_config.sass')
    sass = "// This file is autogenerated by running 'rake configatron:sass'\n"
    sass << "// To customize these settings, edit config.yml > common > sass\n\n"
    configatron.common.sass.to_hash.each_pair do |key, val|
      sass << "$#{key}: #{val}\n"
    end
    File.open(sass_filepath, 'w') {|f| f.write(sass) }
  end

end